### ISSUE TITLE
[셋업] AWS git clone 및 jar 배포 스크립트 작성

### ISSUE THREAD

**Issue by kimjuhyung** [youngcha-lab/liar-game#20]

**Comment by kimjuhyung** [comment]
- AWS EC2 GIT 설치 후 GITGUB에서 CLONE 해오기
- GRADLE로 JAR 생성
- JAR파일 실행
위 내용 포함하는 스크립트 작성

**Comment by sukimzzang** [comment]
@kimjuhyung 참조

**Comment by kyle-log** [comment]
주형이가 업데이트한 커밋 : https://github.com/youngcha-lab/liar-game/commit/78ff2311ecde20cedb1bc938b46d91e351da1f40

@kimjuhyung 
주형아 deploy.sh에서 liar.jar 아니고 liar-game-app-0.0.1-SNAPSHOT.jar 이거 아님??

**Comment by kimjuhyung** [comment]
> 주형이가 업데이트한 커밋 : https://github.com/youngcha-lab/liar-game/commit/78ff2311ecde20cedb1bc938b46d91e351da1f40
> 
> @kimjuhyung 
> 주형아 deploy.sh에서 liar.jar 아니고 liar-game-app-0.0.1-SNAPSHOT.jar 이거 아님??

@kyle-log 
아 아직 이름은 임시로 대충 작성해놓은거고
Gradlew에서 오류나더라구용 오류내용 찍어놔서 파악해볼게요

**Comment by kyle-log** [comment]
@kimjuhyung 

우선 내 로컬에서는 잘 되긴한다

<img width="569" alt="image" src="https://user-images.githubusercontent.com/13461715/150663007-9eed2f51-8656-4b33-a6b0-fa6081cae718.png">

**Comment by kyle-log** [comment]
<img width="302" alt="image" src="https://user-images.githubusercontent.com/13461715/150723035-da46b321-bf52-40a3-92a8-bae4214e743a.png">
