### ISSUE TITLE
방장/ 첫번째 이미지

### ISSUE THREAD

**Issue by Rapha0814** [youngcha-lab/liar-game#49]
- 방장 - 진입 페이지 생성

- [x] 뷰 생성
- [x] 닉네임 EXCEPTION CASE 처리

![ICON](https://user-images.githubusercontent.com/29854777/155840044-0c667ef8-e0c5-4a60-acfb-a90e5bd4dd20.png)

**Comment by sukimzzang** [comment]
api/v1/user 500 통신에러 확인 필요
